[package]
name = "lolbench"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
criterion = "0.2.0"
inflate_0_3_4 = { path = "./inflate_0_3_4" }

[[bench]]
name = "lolbench"
harness = false
path = "src/main.rs"
