[package]
name = "lolbench"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "lolbench"
harness = false
path = "src/main.rs"

