[package]
name = "brotli_1_1_3"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
alloc-no-stdlib = "1.2"
brotli = "=1.1.3"
brotli-decompressor = "=1.2.1"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
