version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Test all
          command: cargo test --release --verbose --all --all-targets
