version: 2
jobs:
  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: apt-get update -y
      - run: apt-get upgrade -y
      - run: apt-get install -y llvm-dev libclang-dev clang
      - restore_cache:
          keys:
            - home_cargo

      - run: cargo test --release --all --all-targets

      - save_cache:
          key: home_cargo
          paths:
            - ~/.cargo
workflows:
  version: 2
  main:
    jobs:
      #TODO deploy lolbench in this workflow
      - test
