version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - home_cargo

      - run: cargo test --release --verbose --all --all-targets

      - save_cache:
          key: home_cargo
          paths:
            - ~/.cargo
