version: 2
anchors:
  - &rust_job
    docker:
      - image: rust:latest

  - &setup
    run:
      name: Set up the environment
      command: git submodule update --init --recursive

  - &install_deps
    run:
      name: Install workspace dependencies
      command: |
        apt-get update -y
        apt-get upgrade -y
        apt-get install -y llvm-dev libclang-dev clang

  - &restore_cache
    restore_cache:
      key: cargo-v0-{{ checksum "Cargo.lock" }}

  - &save_cache
    save_cache:
      key: cargo-v0-{{ checksum "Cargo.lock" }}
      paths:
        - ~/.cargo
        - ~/.rustup


jobs:
  check_formatting:
    <<: *rust_job
    steps:
      - checkout
      - *setup
      - run: rustup component add rustfmt-preview
      - run: cargo fmt-core -- --check

  core_tests:
    <<: *rust_job
    steps:
      - checkout
      - *setup
      - *restore_cache
      - *install_deps
      - run: cargo test-core
      # - run: cargo build --release --all --all-targets
      # - run: cargo test --release --all --all-targets
      - *save_cache

  brotli_1_1_3:
    <<: *rust_job
    steps:
      - checkout
      - *setup
      - *restore_cache
      - *install_deps
      - run:
          name: test benchmark crate
          command: cargo test --release
          working_directory: benches/brotli_1_1_3
      - *save_cache

workflows:
  version: 2
  main:
    jobs:
      #TODO deploy lolbench in this workflow
      - check_formatting
      - core_tests:
          requires:
            - check_formatting
      - brotli_1_1_3:
          requires:
            - check_formatting
