[package]
name = "inflate_0_3_4"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
inflate = "0.3.4"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
