---

- name: ensure_deps
  hosts: all
  remote_user: adam
  become: yes
  become_method: sudo
  tasks:
    # NOTE(anp): uncomment this to update, yeah i agree its dumb
    # - name: apt - update
    #   apt:
    #     update_cache: yes
    # - name: apt - upgrade
    #   apt:
    #     upgrade: yes
    - name: install packages
      apt:
        name: '{{ packages }}'
      vars:
        packages:
          - cpufrequtils
          - git
          - ufw
    - name: firewall - allow ssh
      ufw:
        rule: allow
        port: ssh
    - name: firewall - enable
      ufw:
        state: enabled
        policy: deny
    - name: apt - clean up
      apt:
        autoremove: yes
    - name: apt - more aggressive cleanup
      apt:
        autoclean: yes
    - name: relax perf_event_paranoid
      command: echo 1 > /proc/sys/kernel/perf_event_paranoid
    - name: disable cpu frequency scaling
      copy:
        src: cpufrequtils.default
        dest: /etc/default/cpufrequtils
        owner: root
        group: root
        mode: 0644
    - name: restart cpufrequtils
      systemd:
        name: cpufrequtils
        daemon_reload: yes
        state: restarted
        no_block: yes
    - name: passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - git_config:
        name: user.name
        scope: global
        value: lolbench
    - git_config:
        name: user.email
        scope: global
        value: adam.n.perry+lolbench@gmail.com
    - git_config:
        name: pull.rebase
        scope: global
        value: true
    - name: clone
      git:
        repo: https://github.com/anp/lolbench.git
        dest: '{{ deploy_dir }}'
        refspec: master
        version: '{{ gitsha }}'
      become: yes
      become_user: adam

    - name: systemd-config
      template:
        src: lolbench.service.j2
        dest: /lib/systemd/system/lolbench.service
    - name: systemd-timer
      template:
        src: lolbench.timer.j2
        dest: /lib/systemd/system/lolbench.timer
    - name: systemd-enable
      systemd:
        daemon_reload: yes
        enabled: yes
        name: lolbench.service
    - name: systemd-enable
      systemd:
        daemon_reload: yes
        enabled: yes
        name: lolbench.timer
    - name: systemd-start
      systemd:
        state: restarted
        name: lolbench.timer
