[package]
name = "raytrace_8de9020"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]

[dependencies]
rand = "0.4.2"
lolbench_support = { path = "../../support" }

[dev-dependencies]
lolbench = { path = "../../" }
