[package]
name = "lolbench_extractor"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
marky_mark = { path = "../marky_mark" }
failure = "0.1"
proc-macro-hack = "0.4"
slug = "0.1"
